In [18]:
import numpy as np

import pandas as pd
data= pd.read_csv('GAIL.csv')
print(data)
print(data.dtypes)

            Date Symbol Series  Prev Close    Open    High     Low    Last  \
0     2000-01-03   GAIL     EQ       67.80   65.00   70.00   65.00   68.80
1     2000-01-04   GAIL     EQ       68.70   69.85   72.90   66.00   67.00
2     2000-01-05   GAIL     EQ       66.35   68.35   68.70   61.10   63.00
3     2000-01-06   GAIL     EQ       63.20   64.80   67.00   63.00   64.75
4     2000-01-07   GAIL     EQ       64.95   65.90   65.90   62.00   62.90
...          ...    ...    ...         ...     ...     ...     ...     ...
4980  2021-04-26   GAIL     EQ      129.40  130.70  132.00  129.75  129.90
4981  2021-04-27   GAIL     EQ      130.00  130.00  132.80  130.00  132.00
4982  2021-04-28   GAIL     EQ      131.55  132.50  134.00  132.00  133.00
4983  2021-04-29   GAIL     EQ      133.35  134.70  136.40  133.30  134.75
4984  2021-04-30   GAIL     EQ      134.80  133.45  141.45  132.30  137.25

       Close    VWAP    Volume      Turnover   Trades  Deliverable Volume  \
0      68.70   67.91     76055  5.165166e+11      NaN                 NaN
1      66.35   67.29     98097  6.600457e+11      NaN                 NaN
2      63.20   65.24     92690  6.046889e+11      NaN                 NaN
3      64.95   65.55    173654  1.138299e+12      NaN                 NaN
4      62.65   63.76     86590  5.521388e+11      NaN                 NaN
...      ...     ...       ...           ...      ...                 ...
4980  130.00  130.30   6020366  7.844301e+13  25764.0           1797932.0
4981  131.55  131.77  11823364  1.557963e+14  63157.0           4634336.0
4982  133.35  133.15   6883321  9.165185e+13  30092.0           1535460.0
4983  134.80  134.71   9284829  1.250750e+14  35454.0           3062615.0
4984  137.20  138.26  21349478  2.951761e+14  70416.0           5417740.0

      %Deliverble
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
...           ...
4980       0.2986
4981       0.3920
4982       0.2231
4983       0.3299
4984       0.2538

[4985 rows x 15 columns]
Date                   object
Symbol                 object
Series                 object
Prev Close            float64
Open                  float64
High                  float64
Low                   float64
Last                  float64
Close                 float64
VWAP                  float64
Volume                  int64
Turnover              float64
Trades                float64
Deliverable Volume    float64
%Deliverble           float64
dtype: object

In [55]:
print(data[['Trades',"Deliverable Volume",'%Deliverble']].isnull())

      Trades  Deliverable Volume  %Deliverble
0       True                True         True
1       True                True         True
2       True                True         True
3       True                True         True
4       True                True         True
...      ...                 ...          ...
4980   False               False        False
4981   False               False        False
4982   False               False        False
4983   False               False        False
4984   False               False        False

[4985 rows x 3 columns]

In [56]:
print ("NaN replaced with '0':")
newdataset= data.fillna(0)
print(newdataset)

NaN replaced with '0':
            Date Symbol Series  Prev Close    Open    High     Low    Last  \
0     2000-01-03   GAIL     EQ       67.80   65.00   70.00   65.00   68.80
1     2000-01-04   GAIL     EQ       68.70   69.85   72.90   66.00   67.00
2     2000-01-05   GAIL     EQ       66.35   68.35   68.70   61.10   63.00
3     2000-01-06   GAIL     EQ       63.20   64.80   67.00   63.00   64.75
4     2000-01-07   GAIL     EQ       64.95   65.90   65.90   62.00   62.90
...          ...    ...    ...         ...     ...     ...     ...     ...
4980  2021-04-26   GAIL     EQ      129.40  130.70  132.00  129.75  129.90
4981  2021-04-27   GAIL     EQ      130.00  130.00  132.80  130.00  132.00
4982  2021-04-28   GAIL     EQ      131.55  132.50  134.00  132.00  133.00
4983  2021-04-29   GAIL     EQ      133.35  134.70  136.40  133.30  134.75
4984  2021-04-30   GAIL     EQ      134.80  133.45  141.45  132.30  137.25

       Close    VWAP    Volume      Turnover   Trades  Deliverable Volume  \
0      68.70   67.91     76055  5.165166e+11      0.0                 0.0
1      66.35   67.29     98097  6.600457e+11      0.0                 0.0
2      63.20   65.24     92690  6.046889e+11      0.0                 0.0
3      64.95   65.55    173654  1.138299e+12      0.0                 0.0
4      62.65   63.76     86590  5.521388e+11      0.0                 0.0
...      ...     ...       ...           ...      ...                 ...
4980  130.00  130.30   6020366  7.844301e+13  25764.0           1797932.0
4981  131.55  131.77  11823364  1.557963e+14  63157.0           4634336.0
4982  133.35  133.15   6883321  9.165185e+13  30092.0           1535460.0
4983  134.80  134.71   9284829  1.250750e+14  35454.0           3062615.0
4984  137.20  138.26  21349478  2.951761e+14  70416.0           5417740.0

      %Deliverble
0          0.0000
1          0.0000
2          0.0000
3          0.0000
4          0.0000
...           ...
4980       0.2986
4981       0.3920
4982       0.2231
4983       0.3299
4984       0.2538

[4985 rows x 15 columns]

In [8]:
#print(data.dropna())

            Date Symbol Series  Prev Close    Open    High     Low    Last  \
2529  2011-06-01   GAIL     EQ      444.80  441.30  454.00  441.30  452.40
2530  2011-06-02   GAIL     EQ      452.65  448.00  453.50  441.80  446.65
2531  2011-06-03   GAIL     EQ      447.70  449.70  451.60  437.00  439.30
2532  2011-06-06   GAIL     EQ      439.60  441.50  441.50  431.10  433.00
2533  2011-06-07   GAIL     EQ      432.15  435.00  437.50  431.15  437.50
...          ...    ...    ...         ...     ...     ...     ...     ...
4980  2021-04-26   GAIL     EQ      129.40  130.70  132.00  129.75  129.90
4981  2021-04-27   GAIL     EQ      130.00  130.00  132.80  130.00  132.00
4982  2021-04-28   GAIL     EQ      131.55  132.50  134.00  132.00  133.00
4983  2021-04-29   GAIL     EQ      133.35  134.70  136.40  133.30  134.75
4984  2021-04-30   GAIL     EQ      134.80  133.45  141.45  132.30  137.25

       Close    VWAP    Volume      Turnover   Trades  Deliverable Volume  \
2529  452.65  450.19    558643  2.514971e+13  13902.0            232390.0
2530  447.70  447.21    499302  2.232951e+13  10476.0            274157.0
2531  439.60  443.08    662936  2.937346e+13  13679.0            364792.0
2532  432.15  432.55    705184  3.050277e+13  16917.0            481636.0
2533  435.75  433.50    728729  3.159058e+13  19281.0            436550.0
...      ...     ...       ...           ...      ...                 ...
4980  130.00  130.30   6020366  7.844301e+13  25764.0           1797932.0
4981  131.55  131.77  11823364  1.557963e+14  63157.0           4634336.0
4982  133.35  133.15   6883321  9.165185e+13  30092.0           1535460.0
4983  134.80  134.71   9284829  1.250750e+14  35454.0           3062615.0
4984  137.20  138.26  21349478  2.951761e+14  70416.0           5417740.0

      %Deliverble
2529       0.4160
2530       0.5491
2531       0.5503
2532       0.6830
2533       0.5991
...           ...
4980       0.2986
4981       0.3920
4982       0.2231
4983       0.3299
4984       0.2538

[2456 rows x 15 columns]

In [20]:
data.describe()

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
count,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4.985000e+03,4.985000e+03,2456.000000,4.797000e+03,4797.000000
mean,292.107161,292.555015,297.299248,287.332066,292.135005,292.120090,292.335252,3.100069e+06,7.139141e+13,44548.929967,1.364708e+06,0.527357
std,129.646711,129.714584,131.455571,127.881718,129.622548,129.628103,129.634307,5.865432e+06,9.001079e+13,33130.648961,1.974107e+06,0.158171
min,43.500000,44.800000,45.700000,43.000000,43.750000,43.500000,43.590000,5.000000e+01,3.101000e+08,486.000000,3.792000e+03,0.095700
25%,197.000000,197.450000,201.800000,193.400000,197.000000,197.000000,197.730000,7.347350e+05,2.188007e+13,21391.750000,3.983970e+05,0.421500
50%,326.100000,326.050000,331.800000,321.450000,326.000000,326.100000,326.540000,1.364395e+06,4.595320e+13,35444.500000,7.726460e+05,0.536400
75%,389.100000,389.200000,395.800000,383.400000,388.900000,389.100000,389.330000,2.738720e+06,9.037648e+13,58707.250000,1.494459e+06,0.638100
max,543.600000,545.000000,555.500000,536.050000,545.000000,543.600000,545.280000,1.147153e+08,1.648602e+15,385848.000000,4.549038e+07,1.000000

In [64]:
newdata=newdataset.drop(labels=['Date','Symbol','Series','Turnover','%Deliverble'],axis=1)
print(newdata)

      Prev Close    Open    High     Low    Last   Close    VWAP    Volume  \
0          67.80   65.00   70.00   65.00   68.80   68.70   67.91     76055
1          68.70   69.85   72.90   66.00   67.00   66.35   67.29     98097
2          66.35   68.35   68.70   61.10   63.00   63.20   65.24     92690
3          63.20   64.80   67.00   63.00   64.75   64.95   65.55    173654
4          64.95   65.90   65.90   62.00   62.90   62.65   63.76     86590
...          ...     ...     ...     ...     ...     ...     ...       ...
4980      129.40  130.70  132.00  129.75  129.90  130.00  130.30   6020366
4981      130.00  130.00  132.80  130.00  132.00  131.55  131.77  11823364
4982      131.55  132.50  134.00  132.00  133.00  133.35  133.15   6883321
4983      133.35  134.70  136.40  133.30  134.75  134.80  134.71   9284829
4984      134.80  133.45  141.45  132.30  137.25  137.20  138.26  21349478

       Trades  Deliverable Volume
0         0.0                 0.0
1         0.0                 0.0
2         0.0                 0.0
3         0.0                 0.0
4         0.0                 0.0
...       ...                 ...
4980  25764.0           1797932.0
4981  63157.0           4634336.0
4982  30092.0           1535460.0
4983  35454.0           3062615.0
4984  70416.0           5417740.0

[4985 rows x 10 columns]

In [41]:
x_array = np.array(data['Prev Close'])
new = preprocessing.normalize([x_array])
b=x_array.reshape(-1,1)

print(b)

[[ 67.8 ]
 [ 68.7 ]
 [ 66.35]
 ...
 [131.55]
 [133.35]
 [134.8 ]]

In [71]:
d = preprocessing.normalize(newdata)
scaled_df = pd.DataFrame(d, columns=['Prev Close','Open','High','Low','Last','Close','VWAP','Volume','Trades','Deliverable Volume'])
print(scaled_df)
scaled_df.head(25)

      Prev Close      Open      High       Low      Last     Close      VWAP  \
0       0.000891  0.000855  0.000920  0.000855  0.000905  0.000903  0.000893
1       0.000700  0.000712  0.000743  0.000673  0.000683  0.000676  0.000686
2       0.000716  0.000737  0.000741  0.000659  0.000680  0.000682  0.000704
3       0.000364  0.000373  0.000386  0.000363  0.000373  0.000374  0.000377
4       0.000750  0.000761  0.000761  0.000716  0.000726  0.000724  0.000736
...          ...       ...       ...       ...       ...       ...       ...
4980    0.000021  0.000021  0.000021  0.000021  0.000021  0.000021  0.000021
4981    0.000010  0.000010  0.000010  0.000010  0.000010  0.000010  0.000010
4982    0.000019  0.000019  0.000019  0.000019  0.000019  0.000019  0.000019
4983    0.000014  0.000014  0.000014  0.000014  0.000014  0.000014  0.000014
4984    0.000006  0.000006  0.000006  0.000006  0.000006  0.000006  0.000006

        Volume    Trades  Deliverable Volume
0     0.999997  0.000000            0.000000
1     0.999998  0.000000            0.000000
2     0.999998  0.000000            0.000000
3     1.000000  0.000000            0.000000
4     0.999998  0.000000            0.000000
...        ...       ...                 ...
4980  0.958176  0.004100            0.286151
4981  0.931023  0.004973            0.364928
4982  0.976003  0.004267            0.217717
4983  0.949664  0.003626            0.313248
4984  0.969273  0.003197            0.245967

[4985 rows x 10 columns]

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Trades,Deliverable Volume
0,0.000891,0.000855,0.000920,0.000855,0.000905,0.000903,0.000893,0.999997,0.0,0.0
1,0.000700,0.000712,0.000743,0.000673,0.000683,0.000676,0.000686,0.999998,0.0,0.0
2,0.000716,0.000737,0.000741,0.000659,0.000680,0.000682,0.000704,0.999998,0.0,0.0
3,0.000364,0.000373,0.000386,0.000363,0.000373,0.000374,0.000377,1.000000,0.0,0.0
4,0.000750,0.000761,0.000761,0.000716,0.000726,0.000724,0.000736,0.999998,0.0,0.0
5,0.000736,0.000763,0.000763,0.000729,0.000737,0.000732,0.000738,0.999998,0.0,0.0
6,0.000642,0.000639,0.000643,0.000608,0.000615,0.000616,0.000626,0.999999,0.0,0.0
7,0.000610,0.000640,0.000640,0.000615,0.000630,0.000628,0.000625,0.999999,0.0,0.0
8,0.002186,0.002213,0.002220,0.002176,0.002192,0.002197,0.002198,0.999983,0.0,0.0
9,0.001867,0.001864,0.001899,0.001813,0.001899,0.001885,0.001852,0.999988,0.0,0.0
10,0.000759,0.000772,0.000784,0.000754,0.000775,0.000776,0.000776,0.999998,0.0,0.0
11,0.000905,0.000914,0.000963,0.000902,0.000944,0.000950,0.000927,0.999997,0.0,0.0
12,0.000561,0.000587,0.000587,0.000545,0.000553,0.000551,0.000569,0.999999,0.0,0.0
13,0.001397,0.001391,0.001411,0.001335,0.001347,0.001346,0.001365,0.999993,0.0,0.0
14,0.001104,0.001084,0.001115,0.001080,0.001092,0.001084,0.001091,0.999996,0.0,0.0
15,0.001165,0.001179,0.001202,0.001146,0.001170,0.001163,0.001172,0.999995,0.0,0.0
16,0.000759,0.000748,0.000763,0.000734,0.000745,0.000739,0.000742,0.999998,0.0,0.0
17,0.001584,0.001640,0.001648,0.001583,0.001593,0.001591,0.001600,0.999991,0.0,0.0
18,0.003441,0.003466,0.003466,0.003395,0.003446,0.003444,0.003438,0.999959,0.0,0.0
19,0.002486,0.002461,0.002492,0.002373,0.002402,0.002390,0.002434,0.999979,0.0,0.0
20,0.001678,0.001692,0.001715,0.001672,0.001678,0.001681,0.001692,0.999990,0.0,0.0
21,0.001860,0.001929,0.001967,0.001905,0.001938,0.001938,0.001937,0.999987,0.0,0.0
22,0.000340,0.000338,0.000348,0.000338,0.000342,0.000340,0.000339,1.000000,0.0,0.0
23,0.001451,0.001464,0.001464,0.001405,0.001428,0.001425,0.001423,0.999993,0.0,0.0
24,0.003017,0.002924,0.003060,0.002924,0.002974,0.002962,0.002974,0.999969,0.0,0.0

In [72]:
scaled_df.tail(25)

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Trades,Deliverable Volume
4960,0.000010,0.000010,0.000010,0.000009,0.000009,0.000009,0.000009,0.978467,0.004451,0.206353
4961,0.000009,0.000009,0.000009,0.000009,0.000009,0.000009,0.000009,0.977008,0.004207,0.213159
4962,0.000006,0.000006,0.000006,0.000006,0.000006,0.000006,0.000006,0.980290,0.004292,0.197516
4963,0.000008,0.000008,0.000008,0.000008,0.000008,0.000008,0.000008,0.954721,0.004601,0.297467
4964,0.000002,0.000002,0.000002,0.000002,0.000002,0.000002,0.000002,0.844924,0.001576,0.534884
4965,0.000004,0.000004,0.000004,0.000004,0.000004,0.000004,0.000004,0.985855,0.003707,0.167561
4966,0.000007,0.000007,0.000007,0.000007,0.000007,0.000007,0.000007,0.970240,0.003589,0.242120
4967,0.000011,0.000011,0.000011,0.000010,0.000010,0.000010,0.000010,0.966861,0.004559,0.255262
4968,0.000015,0.000015,0.000016,0.000015,0.000015,0.000015,0.000015,0.984383,0.004691,0.175975
4969,0.000004,0.000004,0.000004,0.000004,0.000004,0.000004,0.000004,0.964602,0.004334,0.263673
4970,0.000009,0.000010,0.000010,0.000009,0.000009,0.000009,0.000010,0.929867,0.003939,0.367875
4971,0.000016,0.000016,0.000016,0.000016,0.000016,0.000016,0.000016,0.980138,0.005054,0.198253
4972,0.000008,0.000008,0.000008,0.000008,0.000008,0.000008,0.000008,0.947264,0.004093,0.320428
4973,0.000006,0.000006,0.000007,0.000006,0.000007,0.000007,0.000007,0.925922,0.003081,0.377702
4974,0.000009,0.000009,0.000009,0.000009,0.000009,0.000009,0.000009,0.955420,0.003832,0.295224
4975,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012,0.949262,0.005317,0.314441
4976,0.000011,0.000011,0.000011,0.000011,0.000011,0.000011,0.000011,0.963345,0.005399,0.268211
4977,0.000006,0.000007,0.000007,0.000006,0.000006,0.000006,0.000006,0.894034,0.004682,0.447974
4978,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012,0.950206,0.004449,0.311590
4979,0.000005,0.000005,0.000005,0.000005,0.000005,0.000005,0.000005,0.892441,0.003843,0.451148
4980,0.000021,0.000021,0.000021,0.000021,0.000021,0.000021,0.000021,0.958176,0.004100,0.286151
4981,0.000010,0.000010,0.000010,0.000010,0.000010,0.000010,0.000010,0.931023,0.004973,0.364928
4982,0.000019,0.000019,0.000019,0.000019,0.000019,0.000019,0.000019,0.976003,0.004267,0.217717
4983,0.000014,0.000014,0.000014,0.000014,0.000014,0.000014,0.000014,0.949664,0.003626,0.313248
4984,0.000006,0.000006,0.000006,0.000006,0.000006,0.000006,0.000006,0.969273,0.003197,0.245967

In [74]:
newdata.describe()

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Trades,Deliverable Volume
count,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4.985000e+03,4985.000000,4.985000e+03
mean,292.107161,292.555015,297.299248,287.332066,292.135005,292.120090,292.335252,3.100069e+06,21948.279238,1.313240e+06
std,129.646711,129.714584,131.455571,127.881718,129.622548,129.628103,129.634307,5.865432e+06,32199.631368,1.953893e+06
min,43.500000,44.800000,45.700000,43.000000,43.750000,43.500000,43.590000,5.000000e+01,0.000000,0.000000e+00
25%,197.000000,197.450000,201.800000,193.400000,197.000000,197.000000,197.730000,7.347350e+05,0.000000,3.612860e+05
50%,326.100000,326.050000,331.800000,321.450000,326.000000,326.100000,326.540000,1.364395e+06,0.000000,7.409870e+05
75%,389.100000,389.200000,395.800000,383.400000,388.900000,389.100000,389.330000,2.738720e+06,34967.000000,1.442336e+06
max,543.600000,545.000000,555.500000,536.050000,545.000000,543.600000,545.280000,1.147153e+08,385848.000000,4.549038e+07